# Generated by Django 4.2.7 on 2023-11-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='num_criteria',
            new_name='number',
        ),
    ]
