# Generated by Django 4.2.7 on 2023-11-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_rename_num_criteria_criteria_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
