# Generated by Django 4.2.7 on 2023-11-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_criteria_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='name',
        ),
    ]
